#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP3EoqaU8ceAQhmoWH1DXuCDHgsv2P2O7Q/ADRtmI8OO pwa@pwa-911AirXD