apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector: 
    app: nexus
  ports:
    - name: web
      port: 8081
      targetPort: 8081
    - name: repo
      port: 8082
      targetPort: 8082

