---
- name: test
  gather_facts: false
  hosts: webservers
  vars:
    ansible_ssh_user: user
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
        - name: Install nginx
          ansible.builtin.apt:
            name: nginx
            state: present
            update_cache: yes
        - name: Start nginx
          service:
            name: nginx
            state: started
            enabled: true
        - name: Copy nginx.conf
          copy: 
              src: ./nginx.conf
              dest: /etc/nginx/nginx.conf
        - name: Copy nginx.conf
          copy: 
              src: ./html
              dest: /var/www/