version: '3.7'

services:
# MASTER
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    env_file: .env
    volumes:
      - ./master/my.cnf:/etc/my.cnf
      - ./master/master.sql:/docker-entrypoint-initdb.d/master.sql
    ports:
      - "3306:3306"
# SLAVE
  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    env_file: .env
    volumes:
      - ./slave/my.cnf:/etc/my.cnf
      - ./slave/slave.sql:/docker-entrypoint-initdb.d/slave.sql
    ports:
      - "3307:3306"
    depends_on:
      - mysql-master
    