apiVersion: v1
kind: Namespace
metadata:
  name: web-token-decoder-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-token-decoder-deployment
  namespace: web-token-decoder-namespace
  labels:
    app: web-token-decoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-token-decoder
  template:
    metadata:
      labels:
        app: web-token-decoder
    spec:
      containers:
      - name: web-token-decoder
        image: pwaawp/web-token-decoder:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "70Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-token-decoder-service
  namespace: web-token-decoder-namespace
  labels:
    app: web-token-decoder
spec:
  type: NodePort
  selector:
    app: web-token-decoder
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
      nodePort: 30007
  # type: ClusterIP